
name: Claude PR Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-code-action:
    if: |
      (
        github.event_name == 'issue_comment' &&
        contains(github.event.comment.body, '@claude') &&
        github.event.comment.user.login == 'Taichi-Ibi'
      ) ||
      (
        github.event_name == 'pull_request_review_comment' &&
        contains(github.event.comment.body, '@claude') &&
        github.event.comment.user.login == 'Taichi-Ibi'
      ) ||
      (
        github.event_name == 'pull_request_review' &&
        contains(github.event.review.body, '@claude') &&
        github.event.review.user.login == 'Taichi-Ibi'
      ) ||
      (
        github.event_name == 'issues' &&
        contains(github.event.issue.body, '@claude') &&
        github.event.issue.user.login == 'Taichi-Ibi'
      )
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude PR Action
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: "60"
          allowed_tools: |
            Bash(chmod:*),
            Bash(curl:*),
            Bash(pip:*),
            Bash(python:*),
            Bash(sh:*)
        env:
          BRAVE_API_KEY: ${{ secrets.BRAVE_API_KEY }}
